from GramAddict.core.plugin_loader import Plugin

# Note: this is mainly here to house old arguments until we figure our args better


class CoreArguments(Plugin):
    """Simply adds core arguments"""

    def __init__(self):
        super().__init__()
        self.description = "Simply adds core arguments"
        self.arguments = [
            {
                "arg": "--device",
                "nargs": None,
                "help": "device identifier. Should be used only when multiple devices are connected at once",
                "metavar": "2443de990e017ece",
                "default": None,
            },
            {
                "arg": "--username",
                "nargs": None,
                "help": "username of the instagram account being used",
                "metavar": "justinbieber",
                "default": None,
            },
            {
                "arg": "--likes-count",
                "nargs": None,
                "help": "number of likes for each interacted user, 1-2 by default. It can be a number (e.g. 2) or a range (e.g. 2-4)",
                "metavar": "2-4",
                "default": "1-2",
            },
            {
                "arg": "--likes-percentage",
                "nargs": None,
                "help": "chance of liking posts on a particular profile, 100 by default. It can be a number (e.g. 20) or a range (e.g. 20-40)",
                "metavar": "50-70",
                "default": "100",
            },
            {
                "arg": "--total-likes-limit",
                "nargs": None,
                "help": "limit on total amount of likes per session, 300 by default",
                "metavar": "300",
                "default": "300",
            },
            {
                "arg": "--total-follows-limit",
                "nargs": None,
                "help": "limit on total follows per session, 50 by default",
                "metavar": "50",
                "default": "50",
            },
            {
                "arg": "--total-unfollows-limit",
                "nargs": None,
                "help": "limit on total unfollows per session, 50 by default",
                "metavar": "50",
                "default": "50",
            },
            {
                "arg": "--total-watches-limit",
                "nargs": None,
                "help": "limit on total watched stories per session, 50 by default",
                "metavar": "50",
                "default": "50",
            },
            {
                "arg": "--total-successful-interactions-limit",
                "nargs": None,
                "help": "limit on total successful interactions per session, 100 by default",
                "metavar": "100",
                "default": "100",
            },
            {
                "arg": "--total-interactions-limit",
                "nargs": None,
                "help": "limit on total interactions per session, 1000 by default",
                "metavar": "1000",
                "default": "1000",
            },
            {
                "arg": "--stories-count",
                "nargs": None,
                "help": "number of stories to watch for each user, 0 by default. It can be a number (e.g. 2) or a range (e.g. 2-4)",
                "metavar": "2-4",
                "default": "0",
            },
            {
                "arg": "--stories-percentage",
                "nargs": None,
                "help": "chance of watching stories on a particular profile, 30-40 by default. It can be a number (e.g. 20) or a range (e.g. 20-40)",
                "metavar": "50-70",
                "default": "30-40",
            },
            {
                "arg": "--carousel-count",
                "nargs": None,
                "help": "number of photos in carousel to watch, 1 by default. It can be a number (e.g. 2) or a range (e.g. 2-4)",
                "metavar": "2-4",
                "default": "1",
            },
            {
                "arg": "--carousel-percentage",
                "nargs": None,
                "help": "chance of watching photos in carousel, 60-70 by default. It can be a number (e.g. 75) or a range (e.g. 60-70)",
                "metavar": "10-90",
                "default": "60-70",
            },
            {
                "arg": "--watch-video-time",
                "nargs": None,
                "help": "amount of time (seconds) you want to watch a video before interact with it, set to 0 to disable this feature. It can be a number (e.g. 20) or a range (e.g. 20-40)",
                "metavar": "15-30",
                "default": "15-30",
            },
            {
                "arg": "--watch-photo-time",
                "nargs": None,
                "help": "amount of time (seconds) you want to watch a photo before interact with it, set to 0 to disable this feature. It can be a number (e.g. 20) or a range (e.g. 20-40)",
                "metavar": "3-4",
                "default": "3-4",
            },
            {
                "arg": "--interactions-count",
                "nargs": None,
                "help": "number of interactions per each blogger, 30-50 by default. It can be a number (e.g. 70) or a range (e.g. 60-80). Only successful interactions count",
                "metavar": "60-80",
                "default": "30-50",
            },
            {
                "arg": "--interact-percentage",
                "nargs": None,
                "help": "chance to interact with user/hashtag or place when applicable (currently in hashtag or place-posts-recent/top)",
                "metavar": "50",
                "default": "50",
            },
            {
                "arg": "--can-reinteract-after",
                "nargs": None,
                "help": "amount of hours that have to pass from the last interaction",
                "metavar": "50",
                "default": None,
            },
            {
                "arg": "--repeat",
                "nargs": None,
                "help": "repeat the same session again after N minutes after completion, disabled by default. It can be a number of minutes (e.g. 180) or a range (e.g. 120-180)",
                "metavar": "220-300",
                "default": None,
            },
            {
                "arg": "--follow-percentage",
                "nargs": None,
                "help": "follow given percentage of interacted users, 0 by default",
                "metavar": "50",
                "default": "0",
            },
            {
                "arg": "--follow-limit",
                "nargs": None,
                "help": "limit on amount of follows per source in each action, disabled by default",
                "metavar": "0",
                "default": None,
            },
            {
                "arg": "--skipped-list-limit",
                "nargs": None,
                "help": "limit how many scrolls tried, with already interacted users, until we move to next source. Does not apply for unfollows",
                "metavar": "10-15",
                "default": "10-15",
            },
            {
                "arg": "--fling-when-skipped",
                "nargs": None,
                "help": 'fling after "X" many scrolls tried, with already interacted users. (not recommended - disabled by default)',
                "metavar": "10-12",
                "default": "0",
            },
            {
                "arg": "--speed-multiplier",
                "nargs": None,
                "help": "modifier for random sleep values - slows down (<1) or speeds up (>1) depending on multiplier passed",
                "metavar": 1,
                "default": 1,
            },
            {
                "arg": "--screen-sleep",
                "help": "save your screen by turning it off during the inactive time, disabled by default",
                "action": "store_true",
            },
            {
                "arg": "--debug",
                "help": "enable debug logging",
                "action": "store_true",
            },
            {
                "arg": "--screen-record",
                "help": "enable screen recording for debugging",
                "action": "store_true",
            },
            {
                "arg": "--close-apps",
                "help": "close all apps except IG, to avoid interference",
                "action": "store_true",
            },
            {
                "arg": "--kill-atx-agent",
                "help": "kill atx-agent when the script ends",
                "action": "store_true",
            },
            {
                "arg": "--restart-atx-agent",
                "help": "restart atx-agent before the script starts",
                "action": "store_true",
            },
            {
                "arg": "--interact",
                "nargs": "+",
                "help": "list of @usernames or #hashtags with whose followers you want to interact",
                "metavar": ("@username1", "@username2"),
                "default": None,
            },
            {
                "arg": "--hashtag-likers",
                "nargs": "+",
                "help": "list of hashtags with whose likers you want to interact",
                "metavar": ("hashtag1", "hashtag2"),
                "default": None,
            },
            {
                "arg": "--delete-interacted-users",
                "help": "delete the user from the file after processing it",
                "action": "store_true",
            },
            {
                "arg": "--scrape-to-file",
                "nargs": None,
                "help": "generate a file in main directory with given name with target users",
                "metavar": ("filename"),
                "default": None,
            },
            {
                "arg": "--total-scraped-limit",
                "nargs": None,
                "help": "limit on total scrape per session, 50 by default",
                "metavar": "5-10",
                "default": "50",
            },
            {
                "arg": "--comment-percentage",
                "nargs": None,
                "help": "comment given percentage of interacted users, 0 by default",
                "metavar": "40-60",
                "default": "0",
            },
            {
                "arg": "--total-comments-limit",
                "nargs": None,
                "help": "limit on total comments per session, disabled by default",
                "metavar": "5-10",
                "default": "0",
            },
            {
                "arg": "--pm-percentage",
                "nargs": None,
                "help": "private message given percentage of interacted users, 0 by default",
                "metavar": "40-60",
                "default": "0",
            },
            {
                "arg": "--total-pm-limit",
                "nargs": None,
                "help": "limit on total private message per session, disabled by default",
                "metavar": "5-10",
                "default": "0",
            },
            {
                "arg": "--max-comments-pro-user",
                "nargs": None,
                "help": "limit on max possible comments for each interacted user",
                "metavar": "1-2",
                "default": "1",
            },
            # ---- AI comments (Gemini) -----------------------------------------------
            # Quando abilitato, prima di pescare un commento dal file txt il bot
            # prova a generarne uno via Gemini API basandosi sulla caption del
            # post. Su qualunque errore (no key, rete, rate-limit, safety block)
            # cade automaticamente sul commento del txt: zero rischio di crash.
            {
                "arg": "--ai-comments-enabled",
                "help": "enable AI-generated comments via Google Gemini (fallback to comments_list.txt on any error)",
                "action": "store_true",
            },
            {
                "arg": "--ai-comments-api-key",
                "nargs": None,
                "help": "Google Gemini API key. If unset, reads env GEMINI_API_KEY / GOOGLE_AI_API_KEY",
                "metavar": "AIzaSy...",
                "default": None,
            },
            {
                "arg": "--ai-comments-model",
                "nargs": None,
                "help": "Gemini model id (default: gemini-2.5-flash-lite). Used as primary; fallback cascade kicks in automatically if it fails.",
                "metavar": "gemini-2.5-flash-lite",
                "default": "gemini-2.5-flash-lite",
            },
            {
                "arg": "--ai-comments-models",
                "nargs": None,
                "help": (
                    "OPTIONAL explicit fallback chain: comma-separated list of Gemini "
                    "models to try in order. If set, OVERRIDES the default cascade. "
                    "Example: 'gemini-2.5-flash-lite,gemini-2.5-flash,gemini-1.5-flash-8b'. "
                    "Leave unset to use the smart default cascade."
                ),
                "metavar": "model1,model2,model3",
                "default": None,
            },
            {
                "arg": "--ai-comments-prompt-hint",
                "nargs": None,
                "help": "free-text hint to bias tone (e.g. 'fitness italian, supportive but not cheesy')",
                "metavar": "...",
                "default": None,
            },
            {
                "arg": "--ai-comments-language",
                "nargs": None,
                "help": "output language for AI comments (default: Italian)",
                "metavar": "Italian",
                "default": "Italian",
            },
            {
                "arg": "--ai-comments-fallback-to-file",
                "help": "if AI generation fails, fall back to comments_list.txt (default: on). Set to false to skip the comment entirely on AI failure.",
                "action": "store_true",
            },
            # ---- AI direct messages (Gemini) ----------------------------------------
            # Personalizza i DM del job dm-followback usando bio + nome + caption
            # ultimo post del destinatario. Fallback su pm_list.txt in caso di
            # errore (rete, rate-limit, safety block, output non conforme).
            # Se ai-dm-enabled non e' settato, eredita da ai-comments-enabled.
            {
                "arg": "--ai-dm-enabled",
                "help": "enable AI-generated personalized DMs via Google Gemini for the dm-followback job (fallback to pm_list.txt on any error). If unset, inherits ai-comments-enabled.",
                "action": "store_true",
            },
            {
                "arg": "--ai-dm-api-key",
                "nargs": None,
                "help": "Google Gemini API key for DMs. If unset, falls back to ai-comments-api-key, then env GEMINI_API_KEY / GOOGLE_AI_API_KEY.",
                "metavar": "AIzaSy...",
                "default": None,
            },
            {
                "arg": "--ai-dm-model",
                "nargs": None,
                "help": "Gemini model id for DMs (default: inherits ai-comments-model). Used as primary; cascade kicks in on failure.",
                "metavar": "gemini-2.5-flash-lite",
                "default": None,
            },
            {
                "arg": "--ai-dm-models",
                "nargs": None,
                "help": "OPTIONAL explicit fallback chain for DMs (comma-separated). Overrides default cascade.",
                "metavar": "model1,model2,model3",
                "default": None,
            },
            {
                "arg": "--ai-dm-prompt-hint",
                "nargs": None,
                "help": "free-text hint about WHO writes the DM (e.g. 'personal trainer / coach in Fiorano Modenese, gym + online'). Critical for relevant personalization.",
                "metavar": "...",
                "default": None,
            },
            {
                "arg": "--ai-dm-language",
                "nargs": None,
                "help": "output language for AI DMs (default: inherits ai-comments-language, then 'Italian').",
                "metavar": "Italian",
                "default": None,
            },
            {
                "arg": "--ai-dm-allow-emoji",
                "nargs": None,
                "help": "allow up to 1-2 light emojis in AI DMs (default: true). Set to 'false' to forbid emojis entirely.",
                "metavar": "true|false",
                "default": "true",
            },
            {
                "arg": "--ai-dm-fetch-bio",
                "nargs": None,
                "help": "extract the recipient bio from the open profile to feed the AI prompt (default: true). Set 'false' to skip (faster, less personalized).",
                "metavar": "true|false",
                "default": "true",
            },
            {
                "arg": "--ai-dm-fallback-to-file",
                "nargs": None,
                "help": "if AI generation fails, fall back to pm_list.txt (default: true). Set 'false' to skip the DM entirely on AI failure.",
                "metavar": "true|false",
                "default": "true",
            },
            # -------------------------------------------------------------------------
            {
                "arg": "--end-if-likes-limit-reached",
                "help": "end session if likes limit is reached",
                "action": "store_true",
            },
            {
                "arg": "--end-if-follows-limit-reached",
                "help": "end session if follows limit is reached",
                "action": "store_true",
            },
            {
                "arg": "--end-if-watches-limit-reached",
                "help": "end session if watches limit is reached",
                "action": "store_true",
            },
            {
                "arg": "--end-if-comments-limit-reached",
                "help": "end session if comments limit is reached",
                "action": "store_true",
            },
            {
                "arg": "--end-if-pm-limit-reached",
                "help": "end session if pm limit is reached",
                "action": "store_true",
            },
            {
                "arg": "--truncate-sources",
                "nargs": None,
                "help": "truncate the source list to a finite number of items",
                "metavar": "2-4",
                "default": "0",
            },
            {
                "arg": "--scroll-skip-start",
                "nargs": None,
                "help": "skip a random number of items at the top of each source list (followers/likers/posts) so the bot doesn't always start from the same users. It can be a number (e.g. 20) or a range (e.g. 10-30).",
                "metavar": "10-30",
                "default": "0",
            },
            {
                "arg": "--resume-from-last-position",
                "help": "remember the last analyzed user (anchor) per source and, on the next run, scroll down until the anchor is found before starting to interact. Avoids re-processing the same users every session.",
                "action": "store_true",
            },
            {
                "arg": "--resume-anchor-search-limit",
                "nargs": None,
                "help": "max number of scrolls used to look for the saved anchor before falling back to --scroll-skip-start.",
                "metavar": "30-60",
                "default": "50",
            },
            {
                "arg": "--resume-cooldown-days",
                "nargs": None,
                "help": "days to wait before re-exploring a source list once it has been fully exhausted (end of list reached).",
                "metavar": "7-30",
                "default": "14",
            },
            {
                "arg": "--hot-zone-screens",
                "nargs": None,
                "help": "[hot-zone] consecutive screens with 0 fresh users that trigger a deep-jump (fling) to escape an already-explored segment. 0 to disable.",
                "metavar": "3",
                "default": "3",
            },
            {
                "arg": "--hot-zone-jump-flings",
                "nargs": None,
                "help": "[hot-zone] number of consecutive flings performed to jump out of a hot zone (~30-50 users skipped per fling).",
                "metavar": "4",
                "default": "4",
            },
            {
                "arg": "--hot-zone-max-jumps",
                "nargs": None,
                "help": "[hot-zone] max number of jump attempts on the same source before abandoning it for the next one.",
                "metavar": "2",
                "default": "2",
            },
            {
                "arg": "--daily-follows-cap",
                "nargs": None,
                "help": "PERSISTENT daily cap on total follows across ALL sessions of the day (survives bot restarts). 0 to disable. When the cap is reached, sessions still run but with follow_limit clipped to 0.",
                "metavar": "70",
                "default": "0",
            },
            {
                "arg": "--daily-likes-cap",
                "nargs": None,
                "help": "PERSISTENT daily cap on total likes across ALL sessions of the day. 0 to disable.",
                "metavar": "150",
                "default": "0",
            },
            {
                "arg": "--daily-unfollows-cap",
                "nargs": None,
                "help": "PERSISTENT daily cap on total unfollows across ALL sessions of the day. 0 to disable.",
                "metavar": "70",
                "default": "0",
            },
            {
                "arg": "--daily-comments-cap",
                "nargs": None,
                "help": "PERSISTENT daily cap on total comments across ALL sessions of the day. 0 to disable.",
                "metavar": "10",
                "default": "0",
            },
            {
                "arg": "--daily-pm-cap",
                "nargs": None,
                "help": "PERSISTENT daily cap on total private messages across ALL sessions of the day. 0 to disable.",
                "metavar": "5",
                "default": "0",
            },
            {
                "arg": "--action-throttle-enabled",
                "help": "[throttle] enforce a minimum interval between consecutive actions of the same type to avoid burst patterns. true by default.",
                "action": "store_true",
                "default": True,
            },
            {
                "arg": "--action-throttle-follow-min",
                "nargs": None,
                "help": "[throttle] minimum seconds between two consecutive follow actions. range supported (e.g. 25-60). 0 to disable.",
                "metavar": "25-60",
                "default": "25-60",
            },
            {
                "arg": "--action-throttle-like-min",
                "nargs": None,
                "help": "[throttle] minimum seconds between two consecutive like actions. range supported (e.g. 8-20). 0 to disable.",
                "metavar": "8-20",
                "default": "8-20",
            },
            {
                "arg": "--action-throttle-unfollow-min",
                "nargs": None,
                "help": "[throttle] minimum seconds between two consecutive unfollow actions.",
                "metavar": "20-45",
                "default": "20-45",
            },
            {
                "arg": "--action-throttle-comment-min",
                "nargs": None,
                "help": "[throttle] minimum seconds between two consecutive comments.",
                "metavar": "60-180",
                "default": "60-180",
            },
            {
                "arg": "--action-throttle-pm-min",
                "nargs": None,
                "help": "[throttle] minimum seconds between two consecutive private messages.",
                "metavar": "120-300",
                "default": "120-300",
            },
            {
                "arg": "--shuffle-jobs",
                "help": "shuffle jobs order",
                "action": "store_true",
            },
            {
                "arg": "--working-hours",
                "nargs": "+",
                "help": "specify working hours",
                "metavar": "10-22",
                "default": ["00.00-23.59"],
            },
            {
                "arg": "--time-delta",
                "nargs": None,
                "help": "delta time to add or subtract from working hours",
                "metavar": "10-15",
                "default": "0",
            },
            {
                "arg": "--disable-filters",
                "help": "disable the using of filters without have to remove/rename the json file",
                "action": "store_true",
            },
            {
                "arg": "--total-crashes-limit",
                "nargs": None,
                "help": "limit on total allowed crashes for session, 5 by default",
                "metavar": "5-10",
                "default": "5",
            },
            {
                "arg": "--count-app-crashes",
                "help": "count as a crash if the app crashes/loses view",
                "action": "store_true",
            },
            {
                "arg": "--skipped-posts-limit",
                "nargs": None,
                "help": "limit on how many skips for posts already interacted are allowed before going to the next job/source, 5 by default",
                "metavar": "5-10",
                "default": "5",
            },
            {
                "arg": "--uia-version",
                "nargs": None,
                "help": "uiautomator version, deprecated.",
                "metavar": 2,
                "default": 2,
            },
            {
                "arg": "--total-sessions",
                "nargs": None,
                "help": "specify how many sessions you want to do before stopping",
                "metavar": 1,
                "default": -1,
            },
            {
                "arg": "--disable-block-detection",
                "help": "disable block detection",
                "action": "store_false",
            },
            {
                "arg": "--pre-script",
                "nargs": "?",
                "help": "specify the path for the pre script",
                "metavar": "",
                "default": None,
                "type": "str",
            },
            {
                "arg": "--post-script",
                "nargs": "?",
                "help": "specify the path for the post script",
                "metavar": "",
                "default": None,
                "type": "str",
            },
            {
                "arg": "--move-folders-in-accounts",
                "help": "allow the script to move all the sibling folders of run.py in accounts folder",
                "action": "store_true",
            },
            {
                "arg": "--dont-type",
                "help": "instead of typing you can paste the text as in old versions",
                "action": "store_true",
            },
            {
                "arg": "--allow-untested-ig-version",
                "help": "don't ask the user to press enter to continue with an untested IG version",
                "action": "store_true",
            },
        ]
